### ISSUE TITLE
Readme.md links to outdated fork

### ISSUE THREAD

**Issue by wind-rider** [ms-iot/pid-controller#6]
The readme.md file refers to an outdated fork of the control loop demo.

It should refer to https://github.com/ms-iot/pid-control-system.

**Comment by IoTGirl** [comment]
Not sure why this is added as an issue and not a pull request.

**Comment by wind-rider** [comment]
@IoTGirl that is because I wrote it from my phone when I came across it and couldn't easily make a PR from there. Maybe next time a more positive comment would be nice?
