### ISSUE TITLE
Readme.md should reflect ControlVariable being time-based

### ISSUE THREAD

**Issue by wind-rider** [ms-iot/pid-controller#7]
The code change in https://github.com/ms-iot/pid-controller/pull/4 is not yet documented in readme.md.

**Comment by IoTGirl** [comment]
Not sure why this is added as an issue and not a pull request.

**Comment by wind-rider** [comment]
Please see the linked PR. I couldn't make a PR from my phone when I wrote that.

**Comment by IoTGirl** [comment]
Closing this based on Merge
