### ISSUE TITLE
Time interval should be in seconds.

### ISSUE THREAD

**Issue by tommallama** [ms-iot/pid-controller#9]
The time interval should probably have units of seconds. This would avoid widely disproportionate gains. As currently coded, if I have a simple controller with parameters Kp = 5, Ki = 3 and Kd =2 derived through some method (Ziegler–Nichols or other) at 1 Hz, the parameters in this implementation would be Kp = 5, Ki = 0.003 and Kd =2000. At the very least changing the units to seconds would ensure you are using a standard unit (always good in science 🙌).

I will see if I can do a bit of testing next week on this code.

Stay awesome,
-Tommallama

**Comment by ooeygui** [comment]
Hi @tommallama ,
You make a good point about standardizing on a time unit. At the same time, I'd also prefer to use double instead of float for better precision, as well as add an autotuning solution. 
(It would also be nice if this was a Windows component so that it could be used by Node.js apps and C++ apps)

**Comment by tommallama** [comment]
I did some testing with a known good implementation of a controller and plant model.  I got this implementation to conform by changing the units of dt to seconds and changing the derivative input to de(t)/dt versus the derivative of the process value. Essentially changed it to conform to the standard parallel PID form. I will do some more testing and post pictures/data tomorrow if I can.

**Comment by tommallama** [comment]
So I've put this implementation in a closed loop of a second order system and compared the response to that of a known good implementation. The tests run are a step command of 5 at 1000ms. There are 3 major items of concern I've identified:

1. The time should be in seconds. Below is a known good controller (my own fixed time implementation) versus this implementation using the same parameters: The orange is this implementation and the green is the known good response.
![asis](https://cloud.githubusercontent.com/assets/8797401/23143839/8a951860-f791-11e6-8cc2-4cac0b5165f2.PNG)
Changing the units to seconds makes the following difference:
![mstos](https://cloud.githubusercontent.com/assets/8797401/23143855/b042fc8a-f791-11e6-9447-db2b1715885f.PNG)
Getting much better.

2. The derivative term is acting on the process value, which is often done to avoid a "derivative kick" when the setpoint changes. This is desirable since the implementation does not include a low-pass filter on the derivative term. With that being said... The sign of the derivative term should then be negative. For more information see http://controlguru.com/pid-control-and-derivative-on-measurement/ specifically the section titled "Derivative on PV is Opposite but Equal". The correct implementations are:
![image](https://cloud.githubusercontent.com/assets/8797401/23144313/b891468c-f794-11e6-8e51-a7357c803907.png)
or 
![image](https://cloud.githubusercontent.com/assets/8797401/23144335/dcc54468-f794-11e6-8c28-248ab7d9c93f.png)

So again,here is the current implementation (modified to seconds as the unit)
![mstos](https://cloud.githubusercontent.com/assets/8797401/23143855/b042fc8a-f791-11e6-9447-db2b1715885f.PNG)

Here is the same controller with the derivative gain acting on the error delta:
![dprocesstoderror](https://cloud.githubusercontent.com/assets/8797401/23144439/95d53fee-f795-11e6-9c6a-04b1d46661ed.PNG)


And here is one with the derivative gain acting on the process value delta but being subtracted instead of added:
![image](https://cloud.githubusercontent.com/assets/8797401/23144425/7b8841f4-f795-11e6-92ad-d40007270485.png)

Now while the 2nd of the three above images appears to follow the baseline controller better, the more desirable one is the last one using the process value delta as the derivative of the error can cause significant instability in some systems as the setpoint is changed. Also I wouldn't expect this the last one to follow my baseline as a gain for the PV delta would be quite different than that of the error.

3. Lastly the naming conventions make the code a bit tricky to follow. 

At any rate I will see if I have some free time this week to make some changes to submit as a pull request.

Remember to be kind to one another
-Tommallama
